# sources are available : https://github.com/Moleculars/Middleware

ARG WINDOWS_TAG=1709

FROM microsoft/powershell:nanoserver as ms
LABEL mongobuilder=true

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV MONGO_VERSION=3.6.8
ENV MONGO_DOWNLOAD_URL=http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${MONGO_VERSION}.zip \
  MONGO_DOWNLOAD_SHA256=2e52e5e848c31985423a81e9ad4334197a3bb0b86d525cb77ba18aaa40658ba0

RUN \
  mkdir C:/TEMP >$null; \
  Write-Host ('Downloading {0} ...' -f $env:MONGO_DOWNLOAD_URL); \
  Invoke-WebRequest -Uri $env:MONGO_DOWNLOAD_URL -OutFile 'C:/TEMP/mongodb.zip' -Proxy $ENV:HTTP_PROXY; \
  Write-Host ('Verifying sha256 ({0}) ...' -f $env:MONGO_DOWNLOAD_SHA256); \
  if ((Get-FileHash C:/TEMP/mongodb.zip -Algorithm sha256).Hash -ne $env:MONGO_DOWNLOAD_SHA256) { \
  Write-Host 'Hash verification of the downloaded file failed'; \
  exit 1; \
  } else { write-host 'Hash verification of the downloaded file is OK'};

RUN \
  Write-Host 'Installing mongodb...'; \
  Expand-Archive -Path C:/TEMP/mongodb.zip -DestinationPath C:\tmp; \
  Move-Item C:\tmp\mongodb-* C:\mongodb; \
  Remove-Item C:\tmp ; \
  Write-Host 'Installation is done in intermediary container';



FROM microsoft/nanoserver:${WINDOWS_TAG}

# Sadly needed because of ### volume permissions. Not needed without volumes.
USER ContainerAdministrator
RUN mkdir C:\data\db && \
  setx PATH %PATH%;C:\mongodb\bin

COPY --from=ms C:/mongodb C:/mongodb
COPY msvcp140.dll vcruntime140.dll C:/windows/system32/
COPY config.dev C:/data/conf/dev.conf
COPY mongo_keyfile C:/data/conf/
COPY healthcheck.bat C:/data/conf/

ENV MONITOR=""
ENV MONITOR_PASS=""

VOLUME C:/data/db

EXPOSE 27017

# set healthcheck
HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=1 CMD ["C:/data/conf/healthcheck.bat"]

# copy necessary files

# set correct entrypoint 
ENTRYPOINT mongod.exe -f C:/data/conf/dev.conf 